// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/rdp.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1932173678;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'connexia_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiInitApp();

  Future<void> crateApiRdpRdpClose({required String sessionId});

  Future<void> crateApiRdpRdpSendKey({
    required String sessionId,
    required int scancode,
    required bool pressed,
    required bool extended,
  });

  Future<void> crateApiRdpRdpSendPointer({
    required String sessionId,
    required int x,
    required int y,
    required int buttons,
    required int wheel,
  });

  Future<void> crateApiRdpRdpSendUnicode({
    required String sessionId,
    required int codepoint,
    required bool pressed,
  });

  Future<void> crateApiRdpRdpSetVisible({
    required String sessionId,
    required bool visible,
  });

  Stream<RdpEvent> crateApiRdpRdpStart({
    required String sessionId,
    required RdpConnectOptions options,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiRdpRdpClose({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdpRdpCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpCloseConstMeta =>
      const TaskConstMeta(debugName: "rdp_close", argNames: ["sessionId"]);

  @override
  Future<void> crateApiRdpRdpSendKey({
    required String sessionId,
    required int scancode,
    required bool pressed,
    required bool extended,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_8(scancode, serializer);
          sse_encode_bool(pressed, serializer);
          sse_encode_bool(extended, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdpRdpSendKeyConstMeta,
        argValues: [sessionId, scancode, pressed, extended],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSendKeyConstMeta => const TaskConstMeta(
    debugName: "rdp_send_key",
    argNames: ["sessionId", "scancode", "pressed", "extended"],
  );

  @override
  Future<void> crateApiRdpRdpSendPointer({
    required String sessionId,
    required int x,
    required int y,
    required int buttons,
    required int wheel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(x, serializer);
          sse_encode_u_16(y, serializer);
          sse_encode_u_8(buttons, serializer);
          sse_encode_i_16(wheel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdpRdpSendPointerConstMeta,
        argValues: [sessionId, x, y, buttons, wheel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSendPointerConstMeta => const TaskConstMeta(
    debugName: "rdp_send_pointer",
    argNames: ["sessionId", "x", "y", "buttons", "wheel"],
  );

  @override
  Future<void> crateApiRdpRdpSendUnicode({
    required String sessionId,
    required int codepoint,
    required bool pressed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(codepoint, serializer);
          sse_encode_bool(pressed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdpRdpSendUnicodeConstMeta,
        argValues: [sessionId, codepoint, pressed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSendUnicodeConstMeta => const TaskConstMeta(
    debugName: "rdp_send_unicode",
    argNames: ["sessionId", "codepoint", "pressed"],
  );

  @override
  Future<void> crateApiRdpRdpSetVisible({
    required String sessionId,
    required bool visible,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_bool(visible, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdpRdpSetVisibleConstMeta,
        argValues: [sessionId, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSetVisibleConstMeta => const TaskConstMeta(
    debugName: "rdp_set_visible",
    argNames: ["sessionId", "visible"],
  );

  @override
  Stream<RdpEvent> crateApiRdpRdpStart({
    required String sessionId,
    required RdpConnectOptions options,
  }) {
    final sink = RustStreamSink<RdpEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_box_autoadd_rdp_connect_options(options, serializer);
            sse_encode_StreamSink_rdp_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiRdpRdpStartConstMeta,
          argValues: [sessionId, options, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRdpRdpStartConstMeta => const TaskConstMeta(
    debugName: "rdp_start",
    argNames: ["sessionId", "options", "sink"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<RdpEvent> dco_decode_StreamSink_rdp_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RdpConnectOptions dco_decode_box_autoadd_rdp_connect_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rdp_connect_options(raw);
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RdpConnectOptions dco_decode_rdp_connect_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RdpConnectOptions(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      domain: dco_decode_opt_String(arr[4]),
      width: dco_decode_u_16(arr[5]),
      height: dco_decode_u_16(arr[6]),
      acceptInvalidCertificates: dco_decode_bool(arr[7]),
    );
  }

  @protected
  RdpEvent dco_decode_rdp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RdpEvent_Connected(
          width: dco_decode_u_16(raw[1]),
          height: dco_decode_u_16(raw[2]),
          certificate: dco_decode_list_prim_u_8_strict(raw[3]),
        );
      case 1:
        return RdpEvent_FrameUpdate(
          x: dco_decode_u_16(raw[1]),
          y: dco_decode_u_16(raw[2]),
          width: dco_decode_u_16(raw[3]),
          height: dco_decode_u_16(raw[4]),
          pixels: dco_decode_list_prim_u_8_strict(raw[5]),
        );
      case 2:
        return RdpEvent_Clipboard(text: dco_decode_String(raw[1]));
      case 3:
        return RdpEvent_Disconnected(reason: dco_decode_String(raw[1]));
      case 4:
        return RdpEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<RdpEvent> sse_decode_StreamSink_rdp_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RdpConnectOptions sse_decode_box_autoadd_rdp_connect_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rdp_connect_options(deserializer));
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RdpConnectOptions sse_decode_rdp_connect_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_domain = sse_decode_opt_String(deserializer);
    var var_width = sse_decode_u_16(deserializer);
    var var_height = sse_decode_u_16(deserializer);
    var var_acceptInvalidCertificates = sse_decode_bool(deserializer);
    return RdpConnectOptions(
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      domain: var_domain,
      width: var_width,
      height: var_height,
      acceptInvalidCertificates: var_acceptInvalidCertificates,
    );
  }

  @protected
  RdpEvent sse_decode_rdp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_width = sse_decode_u_16(deserializer);
        var var_height = sse_decode_u_16(deserializer);
        var var_certificate = sse_decode_list_prim_u_8_strict(deserializer);
        return RdpEvent_Connected(
          width: var_width,
          height: var_height,
          certificate: var_certificate,
        );
      case 1:
        var var_x = sse_decode_u_16(deserializer);
        var var_y = sse_decode_u_16(deserializer);
        var var_width = sse_decode_u_16(deserializer);
        var var_height = sse_decode_u_16(deserializer);
        var var_pixels = sse_decode_list_prim_u_8_strict(deserializer);
        return RdpEvent_FrameUpdate(
          x: var_x,
          y: var_y,
          width: var_width,
          height: var_height,
          pixels: var_pixels,
        );
      case 2:
        var var_text = sse_decode_String(deserializer);
        return RdpEvent_Clipboard(text: var_text);
      case 3:
        var var_reason = sse_decode_String(deserializer);
        return RdpEvent_Disconnected(reason: var_reason);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return RdpEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_rdp_event_Sse(
    RustStreamSink<RdpEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_rdp_connect_options(
    RdpConnectOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rdp_connect_options(self, serializer);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_rdp_connect_options(
    RdpConnectOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_opt_String(self.domain, serializer);
    sse_encode_u_16(self.width, serializer);
    sse_encode_u_16(self.height, serializer);
    sse_encode_bool(self.acceptInvalidCertificates, serializer);
  }

  @protected
  void sse_encode_rdp_event(RdpEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RdpEvent_Connected(
        width: final width,
        height: final height,
        certificate: final certificate,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_16(width, serializer);
        sse_encode_u_16(height, serializer);
        sse_encode_list_prim_u_8_strict(certificate, serializer);
      case RdpEvent_FrameUpdate(
        x: final x,
        y: final y,
        width: final width,
        height: final height,
        pixels: final pixels,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_16(x, serializer);
        sse_encode_u_16(y, serializer);
        sse_encode_u_16(width, serializer);
        sse_encode_u_16(height, serializer);
        sse_encode_list_prim_u_8_strict(pixels, serializer);
      case RdpEvent_Clipboard(text: final text):
        sse_encode_i_32(2, serializer);
        sse_encode_String(text, serializer);
      case RdpEvent_Disconnected(reason: final reason):
        sse_encode_i_32(3, serializer);
        sse_encode_String(reason, serializer);
      case RdpEvent_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
