// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'rdp.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_config`, `connect`, `extract_server_public_key`, `mouse_event`, `pack_rect`, `platform`, `registry`, `run_session`, `send_command`, `tls_upgrade`, `union`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Command`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Starts an RDP session and returns its event stream to Dart.
///
/// The `session_id` is chosen by the caller and is used by the command
/// functions ([`rdp_send_key`], [`rdp_send_pointer`], ...).
Stream<RdpEvent> rdpStart({
  required String sessionId,
  required RdpConnectOptions options,
}) => RustLib.instance.api.crateApiRdpRdpStart(
  sessionId: sessionId,
  options: options,
);

Future<void> rdpSendKey({
  required String sessionId,
  required int scancode,
  required bool pressed,
  required bool extended,
}) => RustLib.instance.api.crateApiRdpRdpSendKey(
  sessionId: sessionId,
  scancode: scancode,
  pressed: pressed,
  extended: extended,
);

Future<void> rdpSendUnicode({
  required String sessionId,
  required int codepoint,
  required bool pressed,
}) => RustLib.instance.api.crateApiRdpRdpSendUnicode(
  sessionId: sessionId,
  codepoint: codepoint,
  pressed: pressed,
);

/// `buttons` is a bitmask: bit 0 left, bit 1 right, bit 2 middle.
/// `wheel` is the signed wheel delta (positive scrolls up).
Future<void> rdpSendPointer({
  required String sessionId,
  required int x,
  required int y,
  required int buttons,
  required int wheel,
}) => RustLib.instance.api.crateApiRdpRdpSendPointer(
  sessionId: sessionId,
  x: x,
  y: y,
  buttons: buttons,
  wheel: wheel,
);

/// Enables or suppresses framebuffer streaming for a session. Used to pause the
/// UI cost of background sessions while keeping the protocol running.
Future<void> rdpSetVisible({
  required String sessionId,
  required bool visible,
}) => RustLib.instance.api.crateApiRdpRdpSetVisible(
  sessionId: sessionId,
  visible: visible,
);

Future<void> rdpClose({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpClose(sessionId: sessionId);

/// Everything required to open an RDP session.
class RdpConnectOptions {
  final String host;
  final int port;
  final String username;
  final String password;
  final String? domain;
  final int width;
  final int height;

  /// Accept any server certificate. The UI is responsible for presenting the
  /// certificate fingerprint and asking the user to trust it before enabling
  /// this (matching the SSH host-key trust flow).
  final bool acceptInvalidCertificates;

  const RdpConnectOptions({
    required this.host,
    required this.port,
    required this.username,
    required this.password,
    this.domain,
    required this.width,
    required this.height,
    required this.acceptInvalidCertificates,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      width.hashCode ^
      height.hashCode ^
      acceptInvalidCertificates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpConnectOptions &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          width == other.width &&
          height == other.height &&
          acceptInvalidCertificates == other.acceptInvalidCertificates;
}

@freezed
sealed class RdpEvent with _$RdpEvent {
  const RdpEvent._();

  const factory RdpEvent.connected({
    required int width,
    required int height,
    required Uint8List certificate,
  }) = RdpEvent_Connected;

  /// Tightly packed RGBA pixels for the rectangle `(x, y, width, height)`.
  const factory RdpEvent.frameUpdate({
    required int x,
    required int y,
    required int width,
    required int height,
    required Uint8List pixels,
  }) = RdpEvent_FrameUpdate;
  const factory RdpEvent.clipboard({required String text}) = RdpEvent_Clipboard;
  const factory RdpEvent.disconnected({required String reason}) =
      RdpEvent_Disconnected;
  const factory RdpEvent.error({required String message}) = RdpEvent_Error;
}
